### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by cs0x7f** [cs0x7f/min2phase#2]
- [x] Cancellation between moves.
- [x] Memory optimization for full phase1 pruning table.
- [x] Tools for full phase1 pruning table.
